# Задание 9

In [1]:
import numpy as np

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [6]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [26]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [12]:
B.shape

(3, 3)

In [27]:
Binv = np.linalg.inv(B)
Binv

LinAlgError: Singular matrix

это вырожденная матрица (определитель=0), для которой нельзя вычислить обратную

# Задание 10

Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [19]:
np.random.seed(42)

# Задание 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно

In [30]:
c = np.random.randint(0, 16, 16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

# Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [32]:
C = c.reshape(4, 4)
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [34]:
D = B + C * 10
D

array([[115, 104,  73, 152],
       [124, 130,  86, 222],
       [123, 226, 239, 362],
       [142, 232, 362, 442]])

In [35]:
d = np.linalg.det(D)
d

62650800.0

In [36]:
r = np.linalg.matrix_rank(D)
r

4

In [38]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01886552, -0.00325327, -0.01147599,  0.00454519],
       [ 0.01683203, -0.02439777,  0.02559361, -0.01449559],
       [ 0.01273886, -0.01565599, -0.00270994,  0.00570208],
       [-0.02532897,  0.02667356, -0.00752744,  0.00374073]])

# Задание 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [39]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 1]])

In [40]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,   9,   5,  32],
       [ 14,   8,  86,  10],
       [ 23,  14,   9, 212],
       [ 11, 122,  15, 302]])