In [1]:
import numpy as np

In [5]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# Задание 2

In [15]:
b1 = a.reshape(3, 4)
print('b1:\n', b1, '\n')

b2 = a.reshape(4, 3)
print('b2:\n', b2, '\n')

b3 = a.reshape(6, 2)
print('b3:\n', b3, '\n')

b4 = a.reshape(2, 6)
print('b4:\n', b4, '\n')

b5 = a.reshape(12, 1)
print('b5:\n', b5, '\n')

b1:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

b2:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

b3:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

b4:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

b5:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 



# Задание 3

In [16]:
с1 = a.reshape(-1, 4)
print('с1:\n', с1, '\n')

с2 = a.reshape(-1, 3)
print('с2:\n', с2, '\n')

с3 = a.reshape(-1, 2)
print('с3:\n', с3, '\n')

с4 = a.reshape(2, -1)
print('с4:\n', с4, '\n')

с5 = a.reshape(12, -1)
print('с5:\n', с5, '\n')

с1:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

с2:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

с3:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

с4:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

с5:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 



# Задание 4

 массив Numpy, состоящий из одного столбца и 12 строк не является одномерным, если каждое значение заключено в [] (по факту является массивом)

# Задание 5

In [18]:
d = np.random.randn(3, 4)
print(d)

[[ 1.45872734 -0.40046089 -0.81731578  0.01533941]
 [-1.22073814  0.26172645  1.32837073  2.50325314]
 [-0.22784716  0.57899771  0.9990516   0.32788032]]


In [20]:
e = d.flatten()
print(e)

[ 1.45872734 -0.40046089 -0.81731578  0.01533941 -1.22073814  0.26172645
  1.32837073  2.50325314 -0.22784716  0.57899771  0.9990516   0.32788032]
