In [1]:
import numpy as np

In [8]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])
a = a.T
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [11]:
mean_a = np.array([a.mean(axis=0)])
mean_a

array([[2. , 8.4]])

In [12]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [17]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [20]:
N = a.size
res = a_centered_sp / (N - 1)
res

0.8888888888888888

In [21]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])